version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network
        depends_on:
            - db
        ports:
            - "9000:9000"

    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        networks:
            - laravel-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    dbdata:
